apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Release.namespace }}
data:
  CFG_PATH: {{ .Values.data.CFG_PATH }}
  CKPT_PATH: {{ .Values.data.CKPT_PATH }}
  LC_ALL: {{ .Values.data.LC_ALL }}
  LOG_LEVEL: {{ .Values.data.LOG_LEVEL }}
  MAX_LENGTH: {{ .Values.data.MAX_LENGTH }}
  MAX_WORKERS: {{ .Values.data.MAX_WORKERS }}
  NVIDIA_DRIVER_CAPABILITIES: {{ .Values.data.NVIDIA_DRIVER_CAPABILITIES }}
  TZ: {{ .Values.data.TZ }}
  CUDA_VISIBLE_DEVICES: {{ .Values.data.CUDA_VISIBLE_DEVICES }}