apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Release.Namespace }}
data:
{{ $currentScope := .}}
{{ range $key, $value := .Values.configMap.data }}
  {{- with $currentScope}}
    {{ $key }}: {{ $value }}
  {{- end }}
{{ end }}