{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "service.labels" .Values.service.labels }}
spec:
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
{{- end }}